#!/usr/bin/env python3
"""Generate random comparison missions from retained models, for differential testing.

    python3 reference/generate_scenarios.py --count 50 --seed 1 --output runs/generated
    python3 reference/reference_check.py --mission-dir runs/generated

Each mission is a seeded draw over: timestep, horizon, motion substeps, entity
families (SimpleAircraft, SingleIntegrator, FixedWing6DOF), start states, update
rates, spawn schedules and positional variance, sensor biases (zero noise), and
interactions (SimpleCollision, GroundCollision, Boundary). Every choice is
comparable: spawn draws use the checker's libc++-compatible stream, sensor noise
is zero, and FixedWing6DOF runs without substeps, where Rust intentionally fixes
AircraftPIDController's C++ timestep bug. Standard library only; the same seed
always writes the same files.
"""

import argparse
from pathlib import Path
import random


def fmt(value):
    return f"{value:.6g}"


def vector(values):
    return " ".join(fmt(value) for value in values)


def sensor_bias(rng, name):
    """Nonzero means with zero standard deviation: deterministic equations only."""
    keys = [f"{kind}_noise_{axis}" for kind in ("pos", "vel", "orient") for axis in range(3)]
    scale = {"pos": 2.0, "vel": 0.5, "orient": 0.05}
    attributes = " ".join(
        f'{key}="{fmt(rng.uniform(-1, 1) * scale[key.split("_")[0]])} 0"' for key in keys)
    return f"<sensor {attributes}>{name}</sensor>"


def aircraft_block(rng, fixed_wing):
    speed = rng.uniform(150, 250) if fixed_wing else rng.uniform(15, 30)
    heading = rng.uniform(-180, 180)
    lines = [f"<heading>{fmt(heading)}</heading>",
             f"<roll>{fmt(rng.uniform(-5, 5))}</roll><pitch>{fmt(rng.uniform(-3, 3))}</pitch>",
             f'<autonomy speed="{fmt(speed)}" loop_rate="{rng.choice([0, 5, 10])}">Straight</autonomy>']
    if fixed_wing:
        lines += [f"<vx>{fmt(speed)}</vx>",  # FixedWing6DOF needs airspeed at start.
                  "<controller>AircraftPIDController</controller>",
                  f'<motion_model wind_E="{fmt(rng.uniform(-3, 3))}" '
                  f'wind_N="{fmt(rng.uniform(-3, 3))}">FixedWing6DOF</motion_model>']
    else:
        lines += [f'<controller loop_rate="{rng.choice([0, 20, 50])}">SimpleAircraftControllerPID</controller>',
                  f'<motion_model turning_radius="{fmt(rng.uniform(20, 60))}">SimpleAircraft</motion_model>']
        if rng.random() < 0.4:
            lines.append(sensor_bias(rng, rng.choice(["NoisyState", "NoisyContacts"])))
    return lines


def point_block(rng):
    velocity = [rng.uniform(-10, 10), rng.uniform(-10, 10), rng.uniform(-2, 2)]
    if rng.random() < 0.1:
        velocity = [0, 0, 0]
    max_speed = rng.choice([-1, -1, round(rng.uniform(1, 12), 3)])
    return [f'<autonomy velocity="{vector(velocity)}" loop_rate="{rng.choice([0, 2, 10])}">'
            "ConstantVelocity</autonomy>",
            "<controller>SingleIntegratorControllerSimple</controller>",
            f'<motion_model max_speed="{fmt(max_speed)}">SingleIntegrator</motion_model>']


def mission(rng, index, horizon=None):
    fixed_wing = rng.random() < 0.2
    dt = 0.01 if fixed_wing else rng.choice([0.05, 0.1])
    multiplier = 1 if fixed_wing else rng.choice([1, 1, 2, 5])
    end = rng.choice([3, 5, 10]) if not fixed_wing else 3
    if horizon is not None:
        # Fixed-wing steps are 0.01 s; cap them at 10,000 steps.
        end = min(horizon, 100) if fixed_wing else horizon
    lines = ['<?xml version="1.0"?>',
             f"<!-- Generated by reference/generate_scenarios.py, scenario {index}. -->",
             f'<runscript name="generated-{index:03}">',
             f'  <run start="0" end="{end}" dt="{dt}" motion_multiplier="{multiplier}" '
             'enable_gui="false" network_gui="false" start_paused="false" time_warp="0" />',
             f"  <seed>{rng.randrange(1, 2**31 - 1)}</seed>",
             "  <end_condition>time</end_condition>",
             "  <network>GlobalNetwork</network><network>LocalNetwork</network>",
             "  <metrics>SimpleCollisionMetrics</metrics>"]
    collisions = rng.random() < 0.5
    if collisions:
        lines.append(f'  <entity_interaction collision_range="{fmt(rng.uniform(1, 20))}">'
                     "SimpleCollision</entity_interaction>")
    if rng.random() < 0.3:
        # Below every start altitude, so startup placement never fails.
        lines.append(f'  <entity_interaction ground_collision_z="{fmt(rng.uniform(0, 90))}">'
                     "GroundCollision</entity_interaction>")
    if not fixed_wing and rng.random() < 0.3:
        lines.append('  <entity_interaction center="0 0 200" lengths="800 800 400" '
                     'show_boundary="false">Boundary</entity_interaction>')
    for block in range(rng.randint(1, 4)):
        count = rng.randint(1, 3)
        position = [rng.uniform(-500, 500), rng.uniform(-500, 500),
                    rng.uniform(100, 300) if not fixed_wing else rng.uniform(800, 1200)]
        variance = [rng.choice([0, 0, 25, 100]), rng.choice([0, 0, 25, 100]), 0]
        if collisions:
            # Entities sharing a start need variance for collision-free placement.
            variance = [max(value, 400) for value in variance[:2]] + [0]
        lines += ["  <entity>",
                  f"    <team_id>{rng.randint(1, 3)}</team_id><count>{count}</count>",
                  f"    <x>{fmt(position[0])}</x><y>{fmt(position[1])}</y><z>{fmt(position[2])}</z>",
                  f"    <variance_x>{variance[0]}</variance_x><variance_y>{variance[1]}</variance_y>"
                  f"<variance_z>0</variance_z>",
                  f"    <variance_heading>{rng.choice([0, 0, 25])}</variance_heading>"]
        if rng.random() < 0.3:
            lines.append("    <use_variance_all_ents>true</use_variance_all_ents>")
        if rng.random() < 0.35:
            lines += [f"    <generate_rate>{fmt(rng.uniform(0.5, 4))}</generate_rate>",
                      f"    <generate_count>{rng.randint(1, 2)}</generate_count>",
                      f"    <generate_start_time>{fmt(rng.uniform(0, 1))}</generate_start_time>",
                      f"    <generate_time_variance>{rng.choice([0, 0.05])}</generate_time_variance>"]
        family = "fixed_wing" if fixed_wing else rng.choice(["aircraft", "point"])
        body = point_block(rng) if family == "point" else aircraft_block(rng, fixed_wing)
        lines += [f"    {line}" for line in body]
        lines += ["    <visual_model>sphere</visual_model>", "  </entity>"]
    lines.append("</runscript>")
    return "\n".join(lines) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--count", type=int, default=50)
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--output", type=Path, required=True, help="new directory")
    parser.add_argument("--horizon", type=float,
                        help="run every scenario for this many seconds (fixed-wing at most 100)")
    args = parser.parse_args(argv)
    args.output.mkdir(parents=True)
    rng = random.Random(args.seed)
    for index in range(args.count):
        (args.output / f"generated-{index:03}.xml").write_text(mission(rng, index, args.horizon))
    print(f"wrote {args.count} missions to {args.output}")


if __name__ == "__main__":
    main()
