#!/usr/bin/env python3
"""Write manuscript tables from retained result data. Standard library only.

Run from the repository root after adding or replacing a retained check:

    python3 paper/data/make_tables.py

Writes paper/manuscript/generated/*.tex. Edit this script, not its output.
"""
import json
import math
import sys
from pathlib import Path

DATA = Path(__file__).resolve().parent
OUTPUT = DATA.parent / "manuscript" / "generated"
# Written by reference/campaign.py; dates and commits are inside each report.
COMPARISON = DATA / "cpp-comparison"
BENCHMARK = DATA / "benchmark" / "timings.json"
GENERATED = DATA / "generated"
LONG = DATA / "generated-long"
PLATFORM = DATA / "platform" / "report.json"
SENSITIVITY = DATA / "sensitivity" / "report.json"
NOISE = DATA / "noise" / "noise-statistics.json"

sys.path.insert(0, str(DATA.parents[1] / "reference"))
from reference_check import comparison_missions  # noqa: E402

# Labels for the agreement table come from reference/missions.txt.
MODELS = {Path(path).name: label for path, label in comparison_missions()}


def number(value):
    """Scientific notation for LaTeX; exact zero stays 0."""
    if value == 0:
        return "0"
    if 1e-2 <= abs(value) < 1e3:
        return f"{value:.3g}"
    exponent = math.floor(math.log10(abs(value)))
    mantissa = value / 10**exponent
    return f"${mantissa:.1f}\\times10^{{{exponent}}}$"


def latex_text(text):
    """Escape the LaTeX specials that appear in defect names and labels."""
    for special in ("\\", "%", "&", "_", "#"):
        text = text.replace(special, "\\" + special)
    return text


def verbatim_name(name):
    return "\\texttt{" + name.replace("_", "\\_") + "}"


def agreement_table():
    rows = []
    for case in sorted(COMPARISON.glob("[0-9]*/result.json")):
        result = json.loads(case.read_text())
        comparison, trace = result["comparison"], result["trace_comparison"]
        name = Path(result["mission"]).name
        explained = result["summary_agreement"] == "explained_by_scoring_rules"
        outcome = "match" + ("\\textsuperscript{a}" if explained else "")
        if not result["passed"]:
            outcome = "differs"
        rows.append(" & ".join([
            verbatim_name(name.removesuffix(".xml")),
            MODELS.get(name, ""),
            str(comparison["compared_entity_states"]),
            number(comparison["max_position_error_m"]),
            number(comparison["max_velocity_error_mps"]),
            number(comparison["max_orientation_error_rad"]),
            str(trace["deliveries"]),
            str(trace["published_states"]),
            str(trace["outputs"]),
            number(trace["max_output_error"]),
            outcome,
        ]) + " \\\\")
    return "\n".join([
        "% Generated by paper/data/make_tables.py; do not edit.",
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{C++/Rust behavioral agreement against the instrumentation branch.",
        "Maximum absolute errors over all compared entity states: position in m,",
        "velocity in m/s, attitude as the rotation angle between orientations in rad.",
        "Trace columns count compared message deliveries, published sensor states,",
        "and plugin output values; every delivery matched in sender, receiver, tick,",
        "and order. In every case the unmodified, instrumented, and traced C++ builds",
        "wrote byte-identical frames and summaries, and Rust outputs were byte-identical",
        "at 1, 2, and 8 workers, with recording, and with tracing.}",
        "\\label{tab:agreement}",
        "\\scriptsize",
        "\\setlength{\\tabcolsep}{2.5pt}",
        "\\begin{tabular}{lP{0.14\\textwidth}rllllrrrll}",
        "\\toprule",
        "& & & \\multicolumn{3}{c}{Frames} & \\multicolumn{4}{c}{Trace} & \\\\",
        "\\cmidrule(lr){4-6}\\cmidrule(lr){7-10}",
        "Mission & Exercises & States & Position & Velocity & Attitude"
        " & Deliv. & Payload & Outputs & Output err. & Result \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}",
        "\\par\\smallskip\\footnotesize",
        "\\textsuperscript{a}The summary differs from C++ and is reproduced exactly by",
        "applying the C++ scoring rule to the Rust run's metrics messages",
        "(Table~\\ref{tab:differences}).",
        "\\end{table*}",
        "",
    ])


def benchmark_table():
    if not BENCHMARK.is_file():
        return None
    timings = json.loads(BENCHMARK.read_text())
    rows = []
    for case in timings["cases"]:
        stats = case["statistics"]
        cells = [verbatim_name(Path(case["mission"]).stem)]
        for variant in ("cpp-1", "rust-1", "rust-8"):
            samples = stats[variant]["samples_s"]
            cells.append(f"{stats[variant]['median_s']:.3f} "
                         f"[{min(samples):.3f}, {max(samples):.3f}]")
        cells.append(f"{stats['rust-1']['cpp_over_rust']:.2f}")
        rows.append(" & ".join(cells) + " \\\\")
    return "\n".join([
        "% Generated by paper/data/make_tables.py; do not edit.",
        "\\begin{table*}[t]",
        "\\centering",
        f"\\caption{{Preliminary whole-process wall time in seconds, median [min, max] of",
        f"{timings['repetitions']} runs after one warm-up, {timings['entities']} aircraft,",
        f"{timings['steps']} steps. Both simulators run under amd64 emulation in one",
        "container; not a native performance result.}",
        "\\label{tab:benchmark}",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\begin{tabular}{lllll}",
        "\\toprule",
        "Mission & C++ (1 thread) & Rust, 1 worker & Rust, 8 workers & Ratio \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}",
        "\\par\\smallskip Ratio: C++ median over Rust one-worker median.",
        "\\end{table*}",
        "",
    ])


def generated_table():
    results = [json.loads(path.read_text()) for path in sorted(GENERATED.glob("*/result.json"))]
    if not results:
        return None
    frames = [result["comparison"] for result in results]
    traces = [result["trace_comparison"] for result in results]
    agreement = [result["summary_agreement"] for result in results]
    # (label, text that appears in a mission only when the feature is used)
    features = [("collisions", ">SimpleCollision<"), ("ground", ">GroundCollision<"),
                ("boundary", ">Boundary<"), ("scheduled spawns", "<generate_rate>"),
                ("NoisyState", ">NoisyState<"), ("NoisyContacts", ">NoisyContacts<"),
                ("fixed-wing", ">FixedWing6DOF<"), ("point-mass", ">SingleIntegrator<")]
    counts = []
    for label, marker in features:
        counts.append(sum(marker in (GENERATED / Path(r["mission"]).name).read_text()
                          for r in results))
    rows = [
        ("Scenarios passing", f"{sum(r['passed'] for r in results)} of {len(results)}"),
        ("Compared entity states", f"{sum(f['compared_entity_states'] for f in frames):,}"),
        ("Compared deliveries / outputs",
         f"{sum(t['deliveries'] for t in traces):,} / {sum(t['outputs'] for t in traces):,}"),
        ("Max position / velocity error",
         f"{number(max(f['max_position_error_m'] for f in frames))} m / "
         f"{number(max(f['max_velocity_error_mps'] for f in frames))} m/s"),
        ("Max attitude / output error",
         f"{number(max(f['max_orientation_error_rad'] for f in frames))} rad / "
         f"{number(max(t['max_output_error'] for t in traces))}"),
        ("Summaries identical / explained",
         f"{agreement.count('agree')} / {agreement.count('explained_by_scoring_rules')}"),
        ("Pre-start removal records excluded",
         str(sum(t['excluded_pre_start_records'] for t in traces))),
        *[(f"Scenarios with {label}", str(count)) for (label, _), count in zip(features, counts)],
    ]
    return "\n".join([
        "% Generated by paper/data/make_tables.py; do not edit.",
        "\\begin{table}[t]",
        "\\centering",
        f"\\caption{{Differential testing over {len(results)} generated scenarios",
        "(\\texttt{generate\\_scenarios.py}, seed 1), with the same checks as",
        "Table~\\ref{tab:agreement}.}",
        "\\label{tab:generated}",
        "\\footnotesize",
        "\\begin{tabularx}{\\columnwidth}{P{0.42\\columnwidth}>{\\raggedright\\arraybackslash}X}",
        "\\toprule",
        *[f"{name} & {value} \\\\" for name, value in rows],
        "\\bottomrule",
        "\\end{tabularx}",
        "\\end{table}",
        "",
    ])


def sensitivity_table():
    if not SENSITIVITY.is_file():
        return None
    report = json.loads(SENSITIVITY.read_text())
    rows = []
    for defect in report["defects"]:
        layers = sorted({layer for found in defect["missions"].values() for layer in found})
        rows.append(f"{latex_text(defect['name'])} & {len(defect['missions'])} & "
                    f"{', '.join(layers) if layers else '\\textbf{missed}'} \\\\")
    detected = sum(defect["detected"] for defect in report["defects"])
    return "\n".join([
        "% Generated by paper/data/make_tables.py; do not edit.",
        "\\begin{table}[t]",
        "\\centering",
        f"\\caption{{Planted defects: {detected} of {len(report['defects'])} detected. Each",
        "is a one-line change applied to a copy of the Rust source and compared",
        "with the saved C++ runs of Table~\\ref{tab:agreement}. Missions counts the",
        "matrix missions that failed; the layers are those that reported it.}",
        "\\label{tab:sensitivity}",
        "\\footnotesize",
        "\\begin{tabularx}{\\columnwidth}{>{\\raggedright\\arraybackslash}Xrl}",
        "\\toprule",
        "Defect & Missions & Detected by \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabularx}",
        "\\end{table}",
        "",
    ])


def noise_table():
    if not NOISE.is_file():
        return None
    report = json.loads(NOISE.read_text())
    rows = []
    for name, quantity in report["quantities"].items():
        rows.append(" & ".join([
            name.replace("_", "\\_"),
            f"{quantity['cpp_mean']:.3f} / {quantity['rust_mean']:.3f}",
            f"{quantity['cpp_std']:.3f} / {quantity['rust_std']:.3f}",
            f"{quantity['ks_statistic']:.4f}", f"{quantity['p_value']:.3f}",
        ]) + " \\\\")
    samples = next(iter(report["quantities"].values()))["cpp_samples"]
    return "\n".join([
        "% Generated by paper/data/make_tables.py; do not edit.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{NoisyContacts error distributions, C++ / Rust, from",
        f"{samples:,} samples per quantity and simulator. Two-sample Kolmogorov-Smirnov",
        f"test; the Bonferroni threshold is {report['per_test_threshold']:.4f}. Position",
        "and velocity errors in m and m/s; attitude as the error rotation angle.}",
        "\\label{tab:noise}",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\begin{tabular}{lllll}",
        "\\toprule",
        "Quantity & Mean & Std. dev. & $D$ & $p$ \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ])


def parity_table():
    """The one-table summary for the main text."""
    matrix = [json.loads(p.read_text()) for p in sorted(COMPARISON.glob("[0-9]*/result.json"))]
    generated = [json.loads(p.read_text()) for p in sorted(GENERATED.glob("*/result.json"))]
    defects = json.loads(SENSITIVITY.read_text())["defects"]
    noise = json.loads(NOISE.read_text())["quantities"]
    long_runs = [json.loads(p.read_text()) for p in sorted(LONG.glob("*/result.json"))]
    divergence = json.loads((LONG / "divergence.json").read_text())["cases"] \
        if (LONG / "divergence.json").is_file() else []
    runs = matrix + generated + long_runs
    passing = [r for r in runs if r["passed"]]
    worst = max(r["comparison"]["max_position_error_m"] for r in passing)
    deliveries = sum(r["trace_comparison"]["deliveries"] for r in runs)
    differing = [r["trace_comparison"].get("delivery_mismatches") for r in runs]
    delivery_note = (f"{sum(differing):,} groups differ" if None not in differing
                     else "mismatch count not recorded in this data")
    rows = [
        ("Curated missions", f"{sum(r['passed'] for r in matrix)} of {len(matrix)} pass"),
        ("Generated scenarios", f"{sum(r['passed'] for r in generated)} of {len(generated)} pass"),
    ]
    if long_runs:
        diverged = [case for case in divergence if case["cpp_vs_rust_exceeds_tolerance_at_s"]]
        detail = " and ".join(f"{case['cpp_vs_rust_exceeds_tolerance_at_s']:.1f} s"
                           for case in diverged)
        rows.append(("Long runs, up to 1,000 s",
                     f"{sum(r['passed'] for r in long_runs)} of {len(long_runs)} pass"
                     + (f"; the others exceed tolerance after {detail}" if diverged else "")))
    rows += [
        ("Planted bugs", f"{sum(d['detected'] for d in defects)} of {len(defects)} detected"),
        ("Sensor noise", f"no difference detected in {sum(q['passed'] for q in noise.values())} "
         f"of {len(noise)} marginal distributions"),
        ("Largest position difference, passing runs", f"{number(worst)} m"),
        ("Message deliveries compared", f"{deliveries:,}; {delivery_note}"),
    ]
    if long_runs and divergence:
        largest = max(case["cpp_vs_rust_final_m"] for case in divergence)
        rows.append(("Largest final difference, long runs", f"{number(largest)} m"))
    return "\n".join([
        "% Generated by paper/data/make_tables.py; do not edit.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Parity evidence. Appendix~\\ref{app:results} has the full results.}",
        "\\label{tab:parity}",
        "\\small",
        "\\begin{tabularx}{\\columnwidth}{P{0.34\\columnwidth}>{\\raggedright\\arraybackslash}X}",
        "\\toprule",
        *[f"{name} & {value} \\\\" for name, value in rows],
        "\\bottomrule",
        "\\end{tabularx}",
        "\\end{table}",
        "",
    ])


def long_table():
    divergence = LONG / "divergence.json"
    if not divergence.is_file():
        return None
    def when(seconds):
        return "never" if seconds is None else f"{seconds:.1f} s"
    rows = []
    for case in json.loads(divergence.read_text())["cases"]:
        rows.append(" & ".join([
            verbatim_name(case["mission"].removesuffix(".xml")), f"{case['end_s']:.0f} s",
            when(case["cpp_vs_rust_exceeds_tolerance_at_s"]),
            when(case["rust_vs_nudged_rust_exceeds_tolerance_at_s"]),
            number(case["cpp_vs_rust_final_m"]),
        ]) + " \\\\")
    return "\n".join([
        "% Generated by paper/data/make_tables.py; do not edit.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Long runs. When C++ and Rust first differ by more than the $10^{-8}$~m",
        "tolerance, and, as a control, when Rust differs from itself after a",
        "one-unit-in-the-last-place change to initial roll, commanded speed, and turning",
        "radius. Final: largest C++/Rust position difference at the end.}",
        "\\label{tab:long}",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{2pt}",
        "\\begin{tabular}{lllll}",
        "\\toprule",
        "Scenario & Length & C++ vs Rust & Rust vs nudged & Final \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ])


def main():
    OUTPUT.mkdir(exist_ok=True)
    long = long_table()
    if long is not None:
        (OUTPUT / "long.tex").write_text(long)
    (OUTPUT / "parity.tex").write_text(parity_table())
    for name, table in (("generated", generated_table()), ("sensitivity", sensitivity_table()),
                        ("noise", noise_table())):
        if table is not None:
            (OUTPUT / f"{name}.tex").write_text(table)
    (OUTPUT / "cpp_agreement.tex").write_text(agreement_table())
    benchmark = benchmark_table()
    if benchmark is not None:
        (OUTPUT / "benchmark.tex").write_text(benchmark)


if __name__ == "__main__":
    main()
